### ISSUE TITLE
Check bài

### ISSUE THREAD

**Issue by HaiYenPham** [LeVanHiep/LeVanHiep.github.io#1]
https://github.com/LeVanHiep/LeVanHiep.github.io/blob/cc141de8211b1babb9f0fde329f5044d64d71378/index.html#L26

bài thì ok rồi, nhưng lười quá, copy hơi nhiều, cũng không sửa màu hay kiểu chữ hay định dạng gì, từ bài sau không thế nữa nha!
 Phần này quan trọng, hầu như sau này lúc nào cũng dùng đến, nên nhớ đọc kỹ nha!

**Comment by LeVanHiep** [comment]
Em sẽ cố gắng edit cho bài sau hấp dẫn hơn ạ 😄 cảm ơn chị vì đã chỉ dẫn cho e. Yêu chị 😍
